// <auto-generated />
using System;
using DecisionMakingSurvey.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DecisionMakingSurvey.Migrations
{
    [DbContext(typeof(DecisionMakingSurveyDBContext))]
    partial class DecisionMakingSurveyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DecisionMakingSurvey.CommandModel.DecisionMakingSurveyCommandModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("DecisionMakingSurveyTable");
                });

            modelBuilder.Entity("DecisionMakingSurvey.CommandModel.ResponsedAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DecisionMakingSurveyCommandModelUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RespondedAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DecisionMakingSurveyCommandModelUserId");

                    b.ToTable("ResponsedAnswer");
                });

            modelBuilder.Entity("DecisionMakingSurvey.CommandModel.ResponsedAnswer", b =>
                {
                    b.HasOne("DecisionMakingSurvey.CommandModel.DecisionMakingSurveyCommandModel", null)
                        .WithMany("Response")
                        .HasForeignKey("DecisionMakingSurveyCommandModelUserId");
                });

            modelBuilder.Entity("DecisionMakingSurvey.CommandModel.DecisionMakingSurveyCommandModel", b =>
                {
                    b.Navigation("Response");
                });
#pragma warning restore 612, 618
        }
    }
}
